# Generated by Django 5.1.7 on 2025-03-26 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kurum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200)),
                ('kurum_turu', models.CharField(choices=[('devlet', 'Devlet Kurumu'), ('ozel', 'Özel Kurum')], max_length=10)),
                ('adres', models.TextField(blank=True, null=True)),
                ('telefon', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('web_sitesi', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
