# Generated by Django 5.1.7 on 2025-03-27 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gonulluler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ilan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200)),
                ('aciklama', models.TextField()),
                ('konum', models.CharField(max_length=200)),
                ('son_basvuru', models.DateField()),
                ('durum', models.CharField(choices=[('aktif', 'Aktif'), ('pasif', 'Pasif'), ('kapali', 'Kapalı')], default='aktif', max_length=10)),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kurum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200)),
                ('adres', models.TextField()),
                ('telefon', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True, null=True)),
                ('aciklama', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Basvuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basvuru_tarihi', models.DateTimeField(auto_now_add=True)),
                ('durum', models.CharField(choices=[('beklemede', 'Beklemede'), ('kabul', 'Kabul Edildi'), ('red', 'Reddedildi')], default='beklemede', max_length=10)),
                ('notlar', models.TextField(blank=True, null=True)),
                ('gonullu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basvurular', to='gonulluler.gonullu')),
                ('ilan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basvurular', to='kurumlar.ilan')),
            ],
        ),
        migrations.AddField(
            model_name='ilan',
            name='kurum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ilanlar', to='kurumlar.kurum'),
        ),
    ]
