# Generated by Django 5.1.7 on 2025-03-26 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kullanici', '0001_initial'),
        ('kurumlar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kullaniciprofil',
            name='kurum',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kurumlar.kurum'),
        ),
    ]
