# Generated by Django 5.1.7 on 2025-03-26 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gonullu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('soyad', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefon', models.CharField(blank=True, max_length=20, null=True)),
                ('aday_turu', models.CharField(choices=[('ogrenci', 'Öğrenci'), ('bireysel', 'Bireysel')], max_length=10)),
                ('dogum_tarihi', models.DateField(blank=True, null=True)),
                ('sehir', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
