# Generated by Django 5.1.7 on 2025-03-27 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gonullu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=30)),
                ('soyad', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('telefon', models.CharField(max_length=20)),
                ('aday_turu', models.CharField(choices=[('ogrenci', 'Öğrenci'), ('bireysel', 'Bireysel')], max_length=10)),
                ('dogum_tarihi', models.DateField(blank=True, null=True)),
                ('sehir', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gonullu', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
