# Generated by Django 5.1.7 on 2025-03-26 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gonulluler', '0001_initial'),
        ('kurumlar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ilan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200)),
                ('aciklama', models.TextField()),
                ('konum', models.CharField(max_length=200)),
                ('baslangic_tarihi', models.DateField()),
                ('bitis_tarihi', models.DateField()),
                ('kontenjan', models.PositiveIntegerField()),
                ('aktif', models.BooleanField(default=True)),
                ('kurum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ilanlar', to='kurumlar.kurum')),
            ],
        ),
        migrations.CreateModel(
            name='Basvuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basvuru_tarihi', models.DateTimeField(auto_now_add=True)),
                ('durum', models.CharField(choices=[('beklemede', 'Beklemede'), ('kabul', 'Kabul Edildi'), ('red', 'Reddedildi')], default='beklemede', max_length=20)),
                ('gonullu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basvurular', to='gonulluler.gonullu')),
                ('ilan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basvurular', to='ilanlar.ilan')),
            ],
        ),
    ]
